config/routes.rb
Rails.application.routes.draw do

  resources :contracts
  get 'contracts_import/new'
  post 'contracts_import/create'

  resources :suppliers, only: [:show]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "contracts#index"

  resources :contracts, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/contract.rb
class Contract < ApplicationRecord
  # Validations
  validates :external_contract_id, presence: true, uniqueness: true
  validates :name, presence: true
  validates :start_date, presence: true
  validates :end_date, presence: true, comparison: {greater_than: :start_date}
  validates :value_cents, presence: true, numericality: {greater_than: 0}

  # Associations
  belongs_to :contract_owner
  belongs_to :supplier

  validates :supplier, presence: true

  monetize :value_cents
end

app/models/contract_owner.rb
class ContractOwner < ApplicationRecord
  # Validations
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true, uniqueness: {case_sensitive: false}, email: {mode: :strict}

  # Associations
  has_many :contracts
end

app/models/supplier.rb
class Supplier < ApplicationRecord
  # Validations
  validates :name, presence: true

  # Associations
  has_many :contracts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contracts_controller.rb
class ContractsController < ApplicationController
  def index
    @contracts = Contract.includes(:contract_owner, :supplier).all
  end
end

app/controllers/contracts_import_controller.rb
require 'csv'

class ContractsImportController < ApplicationController
  def new
  end

  def create
    if params[:csv_file]
      import_csv(params[:csv_file])
      redirect_to contracts_path, notice: "CSV import successful."
    else
      redirect_to contracts_path, alert: "No CSV file selected."
    end
  end

  private

  def import_csv(file)
    CSV.foreach(file.path, headers: true) do |row|
      contract_params = row.to_h

      supplier_name = contract_params["Supplier"].strip
      formatted_name = supplier_name.downcase.gsub(' ', '').gsub(',llc', '').gsub('llc', '')
      supplier = Supplier.find_by("LOWER(REPLACE(name, ' ', '')) LIKE ?", "%#{formatted_name}%")

      supplier ||= Supplier.new(name: contract_params["Supplier"])
      contract_owner = ContractOwner.find_or_initialize_by(email: contract_params["Contract Owner"])

      contract = Contract.find_or_initialize_by(external_contract_id: contract_params["External Contract ID"])

      contract.assign_attributes(
          name: contract_params["Contract Name"],
          contract_owner: contract_owner,
          supplier: supplier,
          start_date: Date.strptime(contract_params["Start Date"], "%m/%d/%Y"),
          end_date: Date.strptime(contract_params["End Date"], "%m/%d/%Y"),
          value_cents: (contract_params["Contract Value"]&.gsub(/[^\d\.]/, '').to_f * 100).to_i
      )

      contract.save
    rescue StandardError => e
      Rails.logger.error("Error importing CSV row: #{e.message}")
    end
  end
end

app/controllers/suppliers_controller.rb
class SuppliersController < ApplicationController
  def show
    @supplier = Supplier.includes(contracts: :contract_owner).find(params[:id])
    @contracts = @supplier.contracts
    @average_contract_value = calculate_average_contract_value(@contracts)
  end

  def calculate_average_contract_value(contracts)
    return 0 if contracts.nil?

    total_value_cents = contracts.sum(:value_cents)
    average_value_cents = total_value_cents / contracts.length
    Money.new(average_value_cents, "USD").format
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contracts/index.html.erb
<div class="table table-auto w-full card-container">
  <div class="table-header-group flex items-center justify-between">
    <div class="table-row bg-white text-gray-800">
      <div class="table-cell text-lg p-4 pl-8">Contracts</div>
      <div class="table-cell"></div>
      <div class="table-cell"></div>
      <div class="table-cell"></div>
      <div class="table-cell"></div>

      <%= link_to "Import Contracts", contracts_import_new_path, data: { turbo_frame: "modal" }, remote: true, class: "rounded-lg py-3 px-8 text-white block font-medium text-center import-contracts" %>
    </div>
  </div>
  <div class="table-header-group">
    <div class="table-row bg-gray-50 text-gray-800 text-sm">
      <div class="table-cell border-t border-gray-300 p-4 pl-8">Contract Owner</div>
      <div class="table-cell border-t border-gray-300 p-4 pl-8">Supplier</div>
      <div class="table-cell border-t border-gray-300 p-4 pl-8">Name</div>
      <div class="table-cell border-t border-gray-300 p-4 pl-8">Start Date</div>
      <div class="table-cell border-t border-gray-300 p-4 pl-8">End Date</div>
      <div class="table-cell border-t border-gray-300 p-4 pl-8">Contract Value</div>
    </div>
  </div>
  <div class="table-row-group">
    <% @contracts.each do |contract| %>
      <div id="<%= dom_id(contract) %>" class="table-row text-gray-600 text-sm">
        <div class="table-cell border-t border-gray-300 p-4 pl-8"><%= "#{contract.contract_owner.first_name} #{contract.contract_owner.last_name}" %></div>
        <div class="table-cell border-t border-gray-300 p-4 pl-8">
          <%= content_tag :div, link_to(contract.supplier&.name, supplier_path(contract.supplier)), class: "text-blue-600" %>
        </div>
        <div class="table-cell border-t border-gray-300 p-4 pl-8"><%= contract.name %></div>
        <div class="table-cell border-t border-gray-300 p-4 pl-8"><%= contract.start_date %></div>
        <div class="table-cell border-t border-gray-300 p-4 pl-8"><%= contract.end_date %></div>
        <div class="table-cell border-t border-gray-300 p-4 pl-8"><%= contract.value.format %></div>
      </div>
    <% end %>
  </div>
</div>

app/views/contracts_import/new.html.erb
<turbo-frame id="modal">
  <div class="modal">
    <div class="modal-title"><b>Import Contracts</b></div>
    <hr style="padding-bottom: 20px;">
    <%= form_with(url: contracts_import_create_path, local: true) do |form| %>
      <%= form.file_field :csv_file, class: "modal-form" %>
      <hr style="padding-bottom: 20px;">
      <div><%= form.submit "Import CSV", class: "modal-button import-csv-btn" %></div>
      <div>
        <%= link_to "Cancel", "#", data: {
          controller: "modals",
          action: "modals#close"
        }, class: "modal-button cancel-button" %>
      </div>

  <% end %>
  </div>
</turbo-frame>

app/views/layouts/_nav.html.erb
<nav class="bg-white border-gray-200 bg-white border-b border-gray-300 fixed w-full top-0">
  <div class="max-w-screen-xl flex flex-wrap items-center justify-between mx-auto p-4">
    <span class="self-center text-2xl font-semibold whitespace-nowrap">Tropic</span>
    <div class="block w-auto" id="navbar-default">
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TropicTakeHome</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="bg-purple-50 h-full w-full">
    <%= render partial: "layouts/nav" %>

    <main class="container mx-auto mt-28 px-5">
      <%= turbo_frame_tag "modal" %>
      <%= render partial: "shared/flash_messages" %>
      <%= yield %>
    </main>
  </body>
</html>

app/views/shared/_flash_messages.html.erb
<% if notice %>
  <p class="notice"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert"><%= alert %></p>
<% end %>

app/views/suppliers/show.html.erb
<%= link_to contracts_path, remote: true, class: "all-contracts font-medium" do %>
  <%= content_tag :svg, xmlns: "http://www.w3.org/2000/svg", viewBox: "0 0 20 20", fill: "currentColor", class: "w-5 h-5 inline-block align-middle mr-2" do %>
    <path fill-rule="evenodd" d="M17 10a.75.75 0 01-.75.75H5.612l4.158 3.96a.75.75 0 11-1.04 1.08l-5.5-5.25a.75.75 0 010-1.08l5.5-5.25a.75.75 0 111.04 1.08L5.612 9.25H16.25A.75.75 0 0117 10z" clip-rule="evenodd" />
  <% end %>
  All Contracts
<% end %>

<div class="table table-auto w-full card-container">
  <div class="table-header-group">
    <div class="table-row bg-white text-gray-800">
      <div class="table-cell text-lg p-4"><%= @supplier.name %> Contracts</div>
      <div class="table-cell"></div>
      <div class="table-cell"></div>
      <div class="table-cell"></div>
      <% if @average_contract_value %>
        <div class="table-cell text-lg p-4">
          <div class="label">Average Contract Value</div>
          <b><%= @average_contract_value %></b>
        </div>
      <% end %>
    </div>
  </div>
  <div class="table-header-group">
    <div class="table-row bg-gray-50 text-gray-800 text-sm">
      <div class="table-cell border-t border-gray-300 p-4 pl-8">Contract Owner</div>
      <div class="table-cell border-t border-gray-300 p-4 pl-8">Name</div>
      <div class="table-cell border-t border-gray-300 p-4 pl-8">Start Date</div>
      <div class="table-cell border-t border-gray-300 p-4 pl-8">End Date</div>
      <div class="table-cell border-t border-gray-300 p-4 pl-8">Contract Value</div>
    </div>
  </div>
  <div class="table-row-group">
    <% @contracts.each do |contract| %>
      <div id="<%= dom_id(contract) %>" class="table-row text-gray-600 text-sm">
        <div class="table-cell border-t border-gray-300 p-4 pl-8"><%= "#{contract.contract_owner.first_name} #{contract.contract_owner.last_name}" %></div>
        <div class="table-cell border-t border-gray-300 p-4 pl-8"><%= contract.name %></div>
        <div class="table-cell border-t border-gray-300 p-4 pl-8"><%= contract.start_date %></div>
        <div class="table-cell border-t border-gray-300 p-4 pl-8"><%= contract.end_date %></div>
        <div class="table-cell border-t border-gray-300 p-4 pl-8"><%= contract.value.format %></div>
      </div>
    <% end %>
  </div>
</div>